version: '3.1'
services:
  mongo:
    build: ./mongodb_rs
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: mongo
        MONGO_INITDB_ROOT_PASSWORD: example
        MONGO_INITDB_DATABASE: mongo
        MONGO_REPLICA_HOST: localhost
        MONGO_REPLICA_PORT: 27017
    ports:
      - '27017:27017'
  app:
    build: ./node_rs
    ports:
      - '3000:3000'
    volumes:
      -.:/app
    environment:
      - NODE_ENV=production