import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import myUser from './actions/getUser'
import Navbar from './(components)/navbar/Navbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const myCurrentUser = await myUser()

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar
        myUser = {myCurrentUser}
        />
        {children}
        </body>
    </html>
  )
}
